Coffee/Models/ChiTietDonHang.cs
namespace Coffee.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class ChiTietDonHang
    {
        public int id { get; set; }

        public int SoLuong { get; set; }

        public decimal? DonGia { get; set; }

        [StringLength(10)]
        public string Size { get; set; }

        [StringLength(1000)]
        public string GhiChu { get; set; }

        public int? id_sanpham { get; set; }

        public int? id_donhang { get; set; }

        public virtual DonHang DonHang { get; set; }

        public virtual SanPham SanPham { get; set; }
    }
}

Coffee/Controllers/QuanTriDonHangController.cs
using Coffee.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace Coffee.Controllers
{
    public class QuanTriDonHangController : AuthenController
    {
        DbContextEntity db = new DbContextEntity();
        // GET: QuanTriDonHang
        public ActionResult Index(int? page, int? pageSize = 10)
        {
            List<DonHang> donHangs = null;
            if (page == null) page = 1;
            donHangs = db.DonHangs.Where(x => x.TrangThai == 0).ToList();

            return View(donHangs.ToPagedList(page.Value, pageSize.Value));
        }

        // GET: QuanTriDonHang
        public ActionResult ChiTietDonHang(int id)
        {
            var donHang = db.DonHangs.FirstOrDefault(x => x.id == id);

            return View(donHang);
        }

        [HttpPost]
        public ActionResult XacNhanDonHang(int? id)
        {
            var donHang = db.DonHangs.FirstOrDefault(x => x.id == id);
            donHang.TrangThai = 1; //Đã xác nhận
            db.SaveChanges();
            return View("ChiTietDonHang", donHang);
        }
        [HttpPost]
        public ActionResult HuyDonHang(int? id)
        {
            var donHang = db.DonHangs.FirstOrDefault(x => x.id == id);
            donHang.TrangThai = -1; //Đã xác nhận
            db.SaveChanges();
            return Json(new {message = "Đã hủy đơn hàng thành công !"});
        }
    }
}

Coffee/Views/QuanTriDonHang/ChiTietDonHang.cshtml
@{
    Layout = "~/Views/Shared/_LayoutQuanTri.cshtml";
}

@using Coffee.Models;
@model DonHang


<script>
    $(document).ready(function () {
        $('.btn-cancel').click(function (e) {
            e.preventDefault();
            $.post("/QuanTriDonHang/HuyDonHang", { id: $(this).data('id') }, function (res) {
                ToastMessage(res.message);
                setTimeout(() => {
                    location.reload();
                }, 500);
            })
        })




    })
</script>


@using (Html.BeginForm("XacNhanDonHang", "QuanTriDonHang", new { id = Model.id }, FormMethod.Post))
{
    <h1>THÔNG TIN ĐƠN HÀNG</h1>
    <div>Khách hàng : <span style="color:darkred; font-weight:700;">@Model.TenKhachHang</span></div>
    <div>Số ĐT:  <span style="color:darkred; font-weight:700;">@Model.SDT</span></div>
    <div>Địa chỉ nhận hàng:  <span style="color:darkred; font-weight:700;">@Model.DiaChiNhanHang</span></div>

    <div class="mt-1"><b>Lưu ý cho đơn hàng:</b>  <span class="red" style="font-weight:700;">@Model.GhiChu</span></div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col">Sản Phẩm</th>
                <th scope="col">Size</th>
                <th scope="col">Số lượng</th>
                <th scope="col">Ghi chú</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ChiTietDonHangs)
            {
                <tr>
                    <td><img src="~/Assets/images/@item.SanPham.HinhAnh" width="100" height="100" /></td>
                    <td>@item.SanPham.TenSanPham</td>
                    <td>@item.Size</td>
                    <td>@item.SoLuong</td>
                    <td>@item.GhiChu</td>
                </tr>
            }

        </tbody>
    </table>
    <div>
        @if (Model.TrangThai == 0)
        {

            <button type="submit" class="btn btn-success btn-confirm pointer">Xác nhận</button>
            <button data-id="@Model.id" class="btn btn-warning btn-cancel pointer">Hủy đơn</button>
        }
        else if (Model.TrangThai == 1)
        {
            <h4 style="color:green;">Đã xác nhận</h4>
        }
        else
        {
            <h4 style="color:red;">Đã hủy đơn</h4>
        }
    </div>

}

Coffee/Views/QuanTriDonHang/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutQuanTri.cshtml";
}


@using PagedList.Mvc;
@model PagedList.IPagedList<Coffee.Models.DonHang>

<style>
    .pagination {
        float: right;
        margin: 0 0 5px;
    }

        .pagination li a {
            border: none;
            font-size: 95%;
            width: 30px;
            height: 30px;
            color: #999;
            margin: 0 2px;
            line-height: 30px;
            border-radius: 30px !important;
            text-align: center;
            padding: 10px 12px;
        }

            .pagination li a:hover {
                color: #666;
            }

        .pagination li.active a {
            background: #03A9F4;
        }

            .pagination li.active a:hover {
                background: #0397d6;
            }

        .pagination li.disabled i {
            color: #ccc;
        }

        .pagination li i {
            font-size: 16px;
            padding-top: 6px
        }
    .value-text {
        color: darkcyan;
        font-weight: 700;
    }

    .value-phone {
        color: darkslategrey;
        font-weight: 700;
    }
</style>
<script>
    $(document).ready(function () {
        $('.xem-chi-tiet').click(function () {
            location.href = '/QuanTriDonHang/ChiTietDonHang?id=' + $(this).data('id');
        })
    })
</script>

@if (Model.Count == 0)
{
    <div class="text-center p-5">Không có đơn hàng</div>
}

@foreach (var item in Model)
{

    <div class="row block-item pl-5">
        <div class="col-12">
            <h3>Đơn hàng: <span class="value-text">@item.id</span></h3>
            <div>Khách hàng: <span class="value-text">@item.TenKhachHang</span></div>
            <div>Số ĐT: <span class="value-phone">@item.SDT</span></div>
            <div>Địa chỉ nhận hàng: <span class="value-text">@item.DiaChiNhanHang</span></div>
            <div>Ngày đặt: <span class="value-text">@item.NgayDatHang</span></div>
            @{
                if (item.TrangThai == 0)
                {
                    <div class="font-weight-bold red">Chờ xác nhận</div>
                }
                else
                {
                    <div class="font-weight-bold red">Đã xác nhận giao hàng</div>
                }
            }

            <button data-id="@item.id" class="btn btn-secondary pointer mt-2 xem-chi-tiet">Chi tiết</button>
        </div>

    </div>
    <hr />
}
<div class="clearfix">
        @Html.PagedListPager(Model, page => Url.Action("Index",
            new { page }))
</div>